# Use postgres/example user/password credentials
version: '3.9'

services:
  
    db:
      image: postgres
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_DB: lms-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5430:5432"
      volumes:
        - type: tmpfs
          target: /dev/shm
          tmpfs:
            size: 134217728 # 128*2^20 bytes = 128Mb
